export const WEB_SOCKET = {
    CONNECTION_START: 'WEB_SOCKET/CONNECTION_START',
    CONNECTION_SUCCESS: 'WEB_SOCKET/CONNECTION_SUCCESS',
    CONNECTION_ERROR: 'WEB_SOCKET/CONNECTION_ERROR',
    CONNECTION_CLOSED: 'WEB_SOCKET/CONNECTION_CLOSED',
    GET_MESSAGE: 'WEB_SOCKET/GET_MESSAGE',
};
