export const WS_ALL_ORDERS_ACTION = {
    CONNECTION_START: 'WS_ALL_ORDERS_ACTION/CONNECTION_START',
    CONNECTION_SUCCESS: 'WS_ALL_ORDERS_ACTION/CONNECTION_SUCCESS',
    CONNECTION_ERROR: 'WS_ALL_ORDERS_ACTION/CONNECTION_ERROR',
    CONNECTION_CLOSED: 'WS_ALL_ORDERS_ACTION/CONNECTION_CLOSED',
    GET_MESSAGE: 'WS_ALL_ORDERS_ACTION/GET_MESSAGE',
};

export const WS_USER_ORDERS_ACTION = {
    CONNECTION_START: 'WS_USER_ORDERS_ACTION/CONNECTION_START',
    CONNECTION_SUCCESS: 'WS_USER_ORDERS_ACTION/CONNECTION_SUCCESS',
    CONNECTION_ERROR: 'WS_USER_ORDERS_ACTION/CONNECTION_ERROR',
    CONNECTION_CLOSED: 'WS_USER_ORDERS_ACTION/CONNECTION_CLOSED',
    GET_MESSAGE: 'WS_USER_ORDERS_ACTION/GET_MESSAGE',
};
