export const WEB_SOCKET_ACTION = {
    CONNECTION_START: 'WEB_SOCKET/CONNECTION_START',
    CONNECTION_SUCCESS: 'WEB_SOCKET/CONNECTION_SUCCESS',
    CONNECTION_ERROR: 'WEB_SOCKET/CONNECTION_ERROR',
    CONNECTION_CLOSED: 'WEB_SOCKET/CONNECTION_CLOSED',
    GET_MESSAGE: 'WEB_SOCKET/GET_MESSAGE',
};

export const WEB_SOCKET_TYPE = {
    ALL_ORDERS: 'WEB_SOCKET_TYPE/ALL_ORDERS',
    USER_ORDERS: 'WEB_SOCKET_TYPE/USER_ORDERS'
};